In [1]:
import numpy as np

In [2]:
np.zeros(5) # create five zeros

array([ 0.,  0.,  0.,  0.,  0.])

In [3]:
np.ones([5,5]) # create 5*5 matrix with 1

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [4]:
np.eye(5) # 5*5 identity matrix 

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [5]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [6]:
np.arange(5,50,2) # 5 to 50 increment by 2

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [8]:
# scalars
arr1 = np.array([[1,2,3,4], [8,9,10,11]])
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [10]:
# indexing
arr1[:] = 1
arr1

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
arr2 = arr1.copy()
arr2

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [13]:
arr2[1][2]

1

In [14]:
arr2[:2,1:] # 1 to everythin columns and everything to the second row (not include second)

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
arr2d = np.zeros((10,10))
arr_length = arr2d.shape[1]
for i in range(arr_length):
    arr2d[i] = i
arr2d
arr2d[[2,4,6,8]] # gives the 2nd,4th,6th,8th row

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [17]:
arr_length = arr2d.shape[1]


10

In [3]:
arr = np.arange(50).reshape((10,5)) # 0 to 49, 10 by 5 matrix
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [4]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [5]:
np.dot(arr.T, arr) # dot product

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [6]:
np.random.randn(10)

array([ 1.39807777,  0.66174017, -0.63528169,  1.10697412,  0.921414  ,
        0.73745386,  0.11598582,  0.06355702, -0.47495972,  0.80452922])

In [8]:
A = np.array([1,2,3,4])
B = np.array([100,200,300,400])
condition = np.array([True,True,False,False])
answer = [(A_val if cond else B_val) for A_val, B_val, cond in zip(A,B,condition)]
answer

[1, 2, 300, 400]

In [10]:
answer2 = np.where(condition,A,B)
answer2

array([  1,   2, 300, 400])

In [11]:
np.where(arr<0,0,arr)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [13]:
arr.sort()
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [15]:
countries = np.array(['F','A','A'])
np.unique(countries)

array(['A', 'F'],
      dtype='<U1')

In [16]:
np.in1d(['A','B'],countries) # whether in

array([ True, False], dtype=bool)